var hotelcity = {
        "hot": [
		    {"Other,Boston":["B", "Boston", "波士顿"]},
		    {"California,Los Angeles":["L", "Los Angeles", "洛杉矶"]},
			{"Other,Hawaii - Oahu Island": ["H", "honolulu", "檀香山"]},
			{"Other,Houston":["H", "Houston", "休斯顿"]},

			{"Florida,Miami":["M", "Miami", "迈阿密"]},
			{"new_york": ["N", "new york", "纽约"]},
			{"Florida,Orlando":["O", "Orlando", "奥兰多"]},
			{"Other,Philadelphia":["P", "Philadelphia", "费城"]},

            {"Other,Salt Lake City":["S","Salt Lake City", "盐湖城"]},
            {"California,San Francisco":["S", "San Francisco", "旧金山"]},
			{"Other,Seattle":["S", "Seattle", "西雅图"]},
            {"Other,Washington DC":["W", "Washington DC", "华盛顿"]},

            {"Other,Denver":["D", "Denver", "丹佛"]},
            {"Other,Chicago":["C", "Chicago", "芝加哥"]},
            {"California,San Diego":["S", "San Diego", "圣地亚哥"]},
            {"Other,New Orleans":["N","New Orleans", "新奥尔良"]},

            {"Las Vegas,Las Vegas":["L", "Las Vegas", "拉斯维加斯"]},		
            {"Other,Detroit":["D", "Detroit", "底特律"]},
            {"Other,Bozeman":["B","Bozeman", "波兹曼(黄石)"]},
            {"Other,Atlanta":["A", "Atlanta", "亚特兰大"]}
    	],
		"A": [
		        {"Other,Akron":["A","Akron"]},
				{"New York,Albany":["A","Albany"]},
				{"Other,Albuquerque":["A","Albuquerque"]},
				{"Other,Alexandria":["A","Alexandria"]},
				{"Other,Allentown":["A","Allentown"]},
				{"Florida,Altamonte Springs":["A","Altamonte Springs"]},
				{"Other,Amarillo":["A","Amarillo"]},
				{"California,Anaheim":["A","Anaheim"]},
				{"Other,Anchorage":["A","Anchorage"]},
				{"Other,Anderson":["A","Anderson"]},
				{"Other,Ann Arbor":["A","Ann Arbor"]},
				{"California,Antioch":["A","Antioch"]},
				{"Florida,Apopka":["A","Apopka"]},
				{"Other,Appleton":["A","Appleton"]},
				{"Other,Asheville":["A","Asheville"]},
				{"Other,Aspen":["A","Aspen"]},
				{"Other,Atlanta":["A","Atlanta", "亚特兰大"]},
				{"Other,Augusta":["A","Augusta"]},
				{"Other,Austin":["A","Austin","奥斯汀"]},
				{"Other,Avoca":["A","Avoca"]}
			],
		"B": [
				{"California,Bakersfield":["B","Bakersfield"]},
				{"Other,Baltimore":["B","Baltimore"]},
				{"Other,Bangor":["B","Bangor"]},
				{"Other,Baton Rouge":["B","Baton Rouge"]},
				{"Other,Beaumont":["B","Beaumont"]},
				{"Other,Bemidji":["B","Bemidji"]},
				{"Other,Bentonville":["B","Bentonville"]},
				{"California,Berkeley":["B","Berkeley"]},
				{"Other,Billings":["B","Billings"]},
				{"Other,Birmingham":["B","Birmingham","伯明翰"]},
				{"Other,Bloomington IL":["B","Bloomington IL"]},
				{"Other,Bloomington IN":["B","Bloomington IN"]},
				{"Florida,Boca Raton":["B","Boca Raton"]},
				{"Other,Boise":["B","Boise","博伊西"]},
				{"Other,Boston":["B","Boston", "波士顿"]},
				{"Other,Bozeman":["B","Bozeman", "波兹曼(黄石)"]},
				{"Florida,Bradenton":["B","Bradenton"]},
				{"Other,Brainerd":["B","Brainerd"]},
				{"Other,Brownsville":["B","Brownsville"]},
				{"New York,Buffalo":["B","Buffalo"]},
				{"California,Burbank":["B","Burbank"]},
				{"California,Burlingame":["B","Burlingame"]},
				{"Other,Burlington":["B","Burlington"]}
			],
		"C": [
				{"Other,Calumet":["C","Calumet"]},
				{"Other,Camp Springs":["C","Camp Springs"]},
				{"Other,Canton":["C","Canton"]},
				{"Florida,Cape Canaveral":["C","Cape Canaveral"]},
				{"Other,Carmel":["","Carmel"]},
				{"Other,Cedar Rapids":["C","Cedar Rapids"]},
				{"Other,Champaign":["C","Champaign"]},
				{"Other,Chandler":["C","Chandler"]},
				{"Other,Charleston - South Carolina":["C","Charleston - South Carolina"]},
				{"Other,Charleston - West Virginia":["C","Charleston - West Virginia"]},
				{"Other,Charlotte":["C","Charlotte"]},
				{"Other,Charlottesville":["C","Charlottesville"]},
				{"Other,Chattanooga":["C","Chattanooga"]},
				{"Other,Chicago":["C","Chicago", "芝加哥"]},
				{"California,Chico":["C","Chico"]},
				{"Other,Cincinnati":["C","Cincinnati","辛辛那提"]},
				{"Florida,Clearwater":["C","Clearwater"]},
				{"Florida,Clermont":["C","Clermont"]},
				{"Other,Cleveland":["C","Cleveland","克利夫兰"]},
				{"Other,Clive":["C","Clive"]},
				{"Other,College Station":["C","College Station"]},
				{"Other,Colorado Springs":["C","Colorado Springs"]},
				{"Other,Columbia":["C","Columbia"]},
				{"Other,Columbus - Georgia":["C","Columbus - Georgia"]},
				{"Other,Columbus - Indiana":["C","Columbus - Indiana"]},
				{"Other,Columbus - Ohio":["C","Columbus - Ohio"]},
				{"California,Concord":["C","Concord"]},
				{"Florida,Coral Springs":["C","Coral Springs"]},
				{"Other,Corpus Christi":["C","Corpus Christi"]}
			],
		"D": [
				{"Other,Dallas":["D","Dallas","达拉斯"]},
				{"Florida,Dania":["D","Dania"]},
				{"Other,Dayton":["D","Dayton"]},
				{"Florida,Daytona Beach":["D","Daytona Beach"]},
				{"California,Del Mar":["D","Del Mar"]},
				{"Florida,Delray Beach":["D","Delray Beach"]},
				{"Other,Denver":["D","Denver", "丹佛"]},
				{"Other,Des Moines":["D","Des Moines"]},
				{"Other,Detroit":["D","Detroit", "底特律"]},
				{"Other,Dothan":["D","Dothan"]},
				{"Other,Duluth":["D","Duluth"]},
				{"Other,Durango":["D","Durango"]},
				{"Other,Durham":["D","Durham"]}
			],
		"E": [
				{"Other,El Paso":["E","El Paso","埃尔帕索"]},
				{"New York,Elmira":["E","Elmira"]},
				{"Other,Erie":["E","Erie"]},
				{"Other,Escanaba":["E","Escanaba"]},
				{"California,Escondido":["E","Escondido"]},
				{"Other,Eugene":["E","Eugene"]},
				{"California,Eureka - Arcata":["E","Eureka - Arcata"]},
				{"Other,Evansville":["E","Evansville"]}
			],
		"F": [
				{"Other,Fairbanks":["F","Fairbanks"]},
				{"Other,Falmouth":["F","Falmouth"]},
				{"Other,Fargo":["F","Fargo"]},
				{"New York,Farmingdale":["F","Farmingdale"]},
				{"Other,Fayetteville - North Carolina":["F","Fayetteville - North Carolina","费耶特维尔"]},
				{"Other,Flagstaff":["F","Flagstaff"]},
				{"Other,Flint":["F","Flint"]},
				{"Florida,Fort Lauderdale":["F","Fort Lauderdale","劳德代尔堡"]},
				{"Florida,Fort Myers":["F","Fort Myers"]},
				{"Other,Fort Smith":["F","Fort Smith"]},
				{"Florida,Fort Walton Beach":["","Fort Walton Beach"]},
				{"Other,Fort Wayne":["F","Fort Wayne"]},
				{"Other,Fort Worth":["F","Fort Worth"]},
				{"California,Foster City":["F","Foster City"]},
				{"California,Fremont":["F","Fremont"]},
				{"California,Fresno":["F","Fresno"]},
				{"California,Fullerton":["F","Fullerton"]}
			],
		"G": [
				{"Florida,Gainesville":["G","Gainesville"]},
				{"Other,Gaithersburg":["G","Gaithersburg"]},
				{"New York,Garden City":["G","Garden City"]},
				{"Other,Glendale":["G","Glendale"]},
				{"Other,Grand Forks":["G","Grand Forks"]},
				{"Other,Grand Island":["G","Grand Island"]},
				{"Other,Grand Junction":["G","Grand Junction"]},
				{"Other,Grand Rapids":["G","Grand Rapids"]},
				{"Other,Great Falls":["G","Great Falls"]},
				{"Other,Green Bay":["G","Green Bay"]},
				{"Other,Greensboro":["G","Greensboro"]},
				{"Other,Greenville":["G","Greenville"]},
				{"Other,Greenwood":["G","Greenwood"]},
				{"Other,Greenwood Village":["G","Greenwood Village"]},
				{"Other,Gulfport":["G","Gulfport"]}
			],
		"H": [
				{"Other,Hawaii - Oahu Island": ["H", "honolulu", "檀香山"]},
				{"Other,Harlingen":["H","Harlingen"]},
				{"Other,Harrisburg":["H","Harrisburg"]},
				{"Other,Hartford":["H","Hartford"]},
				{"Other,Harvey":["H","Harvey"]},
				{"Other,Hawaii - Hawaii Island":["H","Hawaii - Hawaii Island"]},
				{"Other,Hawaii - Kauai Island":["H","Hawaii - Kauai Island"]},
				{"Other,Hawaii - Maui Island":["H","Hawaii - Maui Island"]},
				{"Other,Hawaii - Molokai Island":["H","Hawaii - Molokai Island"]},
				{"Other,Hawaii - Oahu Island":["H","Hawaii - Oahu Island"]},
				{"California,Hayward":["H","Hayward"]},
				{"Other,Helena":["H","Helena"]},
				{"Florida,Hialeah":["H","Hialeah"]},
				{"New York,Hicksville":["H","Hicksville"]},
				{"Other,Hilton Head":["H","Hilton Head"]},
				{"Florida,Hollywood":["H","Hollywood","好莱坞"]},
				{"Florida,Homestead":["H","Homestead"]},
				{"Other,Houghton":["H","Houghton"]},
				{"Other,Houston":["H","Houston", "休斯顿"]},
				{"Other,Hubert Humphrey":["H","Hubert Humphrey"]},
				{"New York,Huntington Station":["H","Huntington Station"]},
				{"Other,Huntsville":["H","Huntsville"]}
			],
		"I": [
				{"Other,Idaho Falls":["I","Idaho Falls","爱达荷福尔斯"]},
				{"Other,Indianapolis":["I","Indianapolis","印第安纳波利斯"]},
				{"Other,International Falls":["I","International Falls"]},
				{"Other,Iselin":["I","Iselin"]},
				{"New York,Islip":["I","Islip"]},
				{"New York,Ithaca":["I","Ithaca"]}
			],
		"J": [
				{"Other,Jackson":["J","Jackson"]},
				{"Other,Jackson Hole":["J","Jackson Hole","杰克逊机场"]},
				{"Other,Jacksonville":["J","Jacksonville"]},
				{"Florida,Jacksonville":["J","Jacksonville"]},
				{"New York,JFK Airport":["J","JFK Airport","肯尼迪机场"]},
				{"Other,Juneau":["J","Juneau"]},
				{"Florida,Jupiter":["J","Jupiter"]},
				{"Other,Kalamazoo":["J","Kalamazoo"]}
			],
		"K": [
				{"Other,Kalispell":["K","Kalispell"]},
				{"Other,Kansas City":["K","Kansas City","堪萨斯城"]},
				{"Other,Kaukauna":["K","Kaukauna"]},
				{"Other,Kerrville":["K","Kerrville"]},
				{"Florida,Key Largo":["K","Key Largo"]},
				{"Florida,Key Largo":["K","Key Largo"]},
				{"Florida,Key West":["K","Key West","基韦斯特"]},
				{"Other,Killeen":["K","Killeen"]},
				{"Florida,Kissimmee":["K","Kissimmee","基西米"]},
				{"Other,Knoxville":["K","Knoxville"]},
				{"Other,Kokomo":["K","Kokomo"]}
			],
		"L": [
				{"Other,La Crosse":["L","La Crosse"]},
				{"New York,La Guardia Airport":["L","La Guardia Airport","拉瓜迪亚机场"]},
				{"Other,Lafayette - Indiana":["L","Lafayette - Indiana"]},
				{"Other,Lafayette - Louisiana":["L","Lafayette - Louisiana"]},
				{"Florida,Lake Buena Vista":["L","Lake Buena Vista"]},
				{"Other,Lake Charles":["L","Lake Charles"]},
				{"Florida,Lakeland":["L","Lakeland"]},
				{"California,Lancaster":["L","Lancaster"]},
				{"Other,Lansing":["L","Lansing"]},
				{"Other,Laredo":["L","Laredo"]},
				{"Florida,Largo":["L","Largo"]},
				{"Las Vegas,Las Vegas":["L","Las Vegas", "拉斯维加斯"]},
				{"Florida,Lauderdale Lakes":["L","Lauderdale Lakes"]},
				{"Other,Lawrenceville":["L","Lawrenceville"]},
				{"Florida,Leesburg":["L","Leesburg"]},
				{"Other,Lewisburg":["L","Lewisburg"]},
				{"Other,Lexington":["L","Lexington"]},
				{"Other,Lincoln":["L","Lincoln"]},
				{"Other,Little Rock":["L","Little Rock","小石城"]},
				{"California,Long Beach":["L","Long Beach", "长滩"]},
				{"California,Los Angeles":["L","Los Angeles", "洛杉矶"]},
				{"Other,Louisville":["L","Louisville"]},
				{"Other,Lubbock":["L","Lubbock"]}
			],
		"M": [
				{"Other,Macon":["M","Macon"]},
				{"Other,Madison":["M","Madison","麦迪逊"]},
				{"Other,Manchester":["M","Manchester","曼彻斯特"]},
				{"New York,Manhattan":["M","Manhattan","曼哈顿"]},
				{"Florida,Marathon":["M","Marathon"]},
				{"Florida,Margate":["M","Margate"]},
				{"Other,Marquette":["M","Marquette"]},
				{"Other,Marshall":["M","Marshall"]},
				{"Other,McAllen":["M","McAllen"]},
				{"Other,Medford":["M","Medford"]},
				{"Florida,Melbourne":["M","Melbourne"]},
				{"Other,Memphis":["M","Memphis","孟菲斯"]},
				{"California,Merced":["M","Merced"]},
				{"Other,Mesa":["M","Mesa"]},
				{"Florida,Miami":["M","Miami", "迈阿密"]},
				{"Other,Midland":["M","Midland"]},
				{"California,Milpitas":["M","Milpitas"]},
				{"Other,Milwaukee":["M","Milwaukee","密尔沃基"]},
				{"Other,Minneapolis":["M","Minneapolis","明尼阿波利斯"]},
				{"Other,Minot":["M","Minot"]},
				{"Other,Missoula":["M","Missoula"]},
				{"Other,Mobile":["M","Mobile"]},
				{"California,Modesto":["M","Modesto"]},
				{"Other,Monroe":["M","Monroe"]},
				{"California,Monterey":["M","Monterey"]},
				{"Other,Montgomery":["M","Montgomery","蒙哥马利"]},
				{"Other,Montrose":["M","Montrose"]},
				{"Other,Mosinee":["M","Mosinee"]},
				{"Other,Muncie":["M","Muncie"]},
				{"Other,Muskegon":["M","Muskegon"]},
				{"Other,Myrtle Beach":["M","Myrtle Beach","默特尔比奇"]}
			],
		"N": [
				{"new_york": ["N", "new york", "纽约"]},
				{"New York,Nanuet":["N","Nanuet"]},
				{"California,Napa":["N","Napa"]},
				{"Other,Naperville":["N","Naperville","纳什维尔"]},
				{"Florida,Naples":["N","Naples"]},
				{"Other,Nashville":["N","Nashville"]},
				{"Other,New Bern":["N","New Bern"]},
				{"Other,New Haven":["N","New Haven"]},
				{"Other,New Orleans":["N","New Orleans", "新奥尔良"]},
				{"Florida,New Smyrna Beach":["N","New Smyrna Beach"]},
				{"New York,New Windsor":["N","New Windsor"]},
				{"Other,Newark":["N","Newark","纽瓦克"]},
				{"California,Newport Beach":["N","Newport Beach"]},
				{"Other,Newport News":["N","Newport News"]},
				{"Other,Norcross":["N","Norcross"]},
				{"Other,Norfolk":["N","Norfolk"]},
				{"Other,North Canton":["N","North Canton"]},
				{"Other,North Platte":["N","North Platte"]},
				{"Other,Northglenn":["N","Northglenn"]}
			],
		"O": [
				{"California,Oakland":["O","Oakland","奥克兰"]},
				{"Florida,Ocala":["O","Ocala"]},
				{"Other,Oklahoma City":["O","Oklahoma City","奥克拉荷马城"]},
				{"Other,Omaha":["O","Omaha","奥马哈"]},
				{"California,Ontario":["O","Ontario"]},
				{"Florida,Orange City":["O","Orange City"]},
				{"California,Orange County":["O","Orange County"]},
				{"Florida,Orange Park":["O","Orange Park"]},
				{"Florida,Orlando":["O","Orlando", "奥兰多"]},
				{"Florida,Orlando International Airport":["O","Orlando International Airport","奥兰多国际机场"]},
				{"California,Oxnard":["O","Oxnard"]}
			],
		"P": [
				{"Florida,Palm Bay":["P","Palm Bay"]},
				{"California,Palm Springs":["P","Palm Springs"]},
				{"Florida,Panama City":["P","Panama City"]},
				{"Florida,Panama City Beach":["P","Panama City Beach"]},
				{"Other,Pasco":["P","Pasco"]},
				{"Florida,Pembroke Pines":["P","Pembroke Pines"]},
				{"Florida,Pensacola":["P","Pensacola"]},
				{"Other,Peoria":["P","Peoria"]},
				{"Other,Philadelphia":["P","Philadelphia", "费城"]},
				{"Other,Phoenix":["P","Phoenix","菲尼克斯"]},
				{"Other,Pittsburgh":["P","Pittsburgh","匹斯堡"]},
				{"Florida,Pompano Beach":["P","Pompano Beach"]},
				{"Florida,Port Charlotte":["P","Port Charlotte"]},
				{"Florida,Port Richey":["P","Port Richey"]},
				{"Other,Portland Maine":["P","Portland Maine"]},
				{"Other,Portland Oregon":["P","Portland Oregon","波特兰"]},
				{"New York,Poughkeepsie":["P","Poughkeepsie"]},
				{"Other,Providence":["P","Providence"]},
				{"Florida,Punta Gorda":["P","Punta Gorda"]}
			],
		"Q": [],
		"R": [
				{"Other,Raleigh":["R","Raleigh"]},
				{"Other,Rapid City":["R","Rapid City","拉皮德城"]},
				{"California,Redwood City":["R","Redwood City"]},
				{"Las Vegas,Reno":["R","Reno","雷诺"]},
				{"Other,Rhinelander":["R","Rhinelander"]},
				{"Other,Richmond":["R","Richmond","里士满"]},
				{"California,Riverside":["R","Riverside","里弗赛德"]},
				{"Other,Roanoke":["R","Roanoke"]},
				{"New York,Rochester":["R","Rochester"]},
				{"Other,Rockford":["R","Rockford"]},
				{"Other,Rocky Mount":["R","Rocky Mount"]},
				{"New York,Rome":["R","Rome"]}
			],
		"S": [
				{"California,Sacramento":["S","Sacramento","萨克拉门托"]},
				{"Other,Saginaw":["S","Saginaw"]},
				{"Other,Saint Louis":["S","Saint Louis","圣路易斯"]},
				{"Other,Salt Lake City":["S","Salt Lake City", "盐湖城"]},
				{"Other,San Antonio":["S","San Antonio","圣安东尼奥"]},
				{"California,San Diego":["S","San Diego", "圣地亚哥"]},
				{"California,San Francisco":["S","San Francisco", "旧金山"]},
				{"California,San Jose":["S","San Jose"]},
				{"California,San Ramon":["S","San Ramon"]},
				{"Florida,Sanford":["S","Sanford"]},
				{"California,Santa Barbara":["S","Santa Barbara","圣巴巴拉"]},
				{"California,Santa Rosa":["S","Santa Rosa"]},
				{"Florida,Sarasota":["S","Sarasota"]},
				{"Other,Savannah":["S","Savannah"]},
				{"Other,Scottsdale":["S","Scottsdale"]},
				{"Other,Scranton":["S","Scranton"]},
				{"Other,Seattle":["S","Seattle", "西雅图"]},
				{"Other,Shreveport":["S","Shreveport"]},
				{"Other,Sioux City":["S","Sioux City","苏城"]},
				{"Other,Sioux Falls":["S","Sioux Falls"]},
				{"Other,Smyrna":["S","Smyrna"]},
				{"California,Solana Beach":["S","Solana Beach"]},
				{"Other,South Bend":["S","South Bend"]},
				{"Other,South Burlington":["S","South Burlington"]},
				{"Other,Spokane":["S","Spokane"]},
				{"Other,Springfield":["S","Springfield"]},
				{"Florida,St Augustine":["S","St Augustine"]},
				{"Florida,St Petersburg":["S","St Petersburg"]},
				{"Other,Stamford":["S","Stamford"]},
				{"Other,State College":["S","State College"]},
				{"Florida,Stuart":["S","Stuart"]},
				{"Florida,Sunrise":["S","Sunrise"]},
				{"New York,Syracuse":["S","Syracuse"]}
			],
		"T": [
				{"Florida,Tallahassee":["T","Tallahassee"]},
				{"Florida,Tampa":["T","Tampa","坦帕"]},
				{"Other,Telluride":["T","Telluride"]},
				{"California,Temecula":["T","Temecula"]},
				{"Other,Tempe":["T","Tempe"]},
				{"Other,Temple":["T","Temple"]},
				{"Florida,Tequesta":["T","Tequesta"]},
				{"Other,Terre Haute":["T","Terre Haute"]},
				{"Florida,Titusville":["T","Titusville"]},
				{"Other,Toledo":["T","Toledo"]},
				{"California,Torrance":["T","Torrance"]},
				{"California,Tracy":["T","Tracy"]},
				{"Other,Traverse City":["T","Traverse City"]},
				{"Other,Tri City":["T","Tri City"]},
				{"Other,Tucson":["T","Tucson"]},
				{"Other,Tulsa":["T","Tulsa"]},
				{"Other,Twin Falls":["T","Twin Falls"]},
				{"Other,Tyler":["T","Tyler"]}
			],
		"U": [],
		"V": [
				{"Other,Vail Eagle":["V","Vail Eagle"]},
				{"California,Vallejo":["V","Vallejo"]},
				{"Florida,Venice":["V","Venice"]},
				{"Florida,Vero Beach":["V","Vero Beach"]},
				{"Other,Vienna":["V","Vienna"]},
				{"California,Visalia":["V","Visalia"]}
			],
		"W": [
				{"Other,Waco":["W","Waco",""]},
				{"California,Walnut Creek":["W","Walnut Creek"]},
				{"Other,Warwick":["W","Warwick"]},
				{"Other,Washington DC":["W","Washington DC", "华盛顿"]},
				{"Florida,West Palm Beach":["W","West Palm Beach"]},
				{"New York,Westchester":["W","Westchester"]},
				{"New York,White Plains":["W","White Plains"]},
				{"Other,Wichita":["W","Wichita"]},
				{"Other,Wilmington - Delaware":["W","Wilmington - Delaware"]},
				{"Other,Wilmington - North Carolina":["W","Wilmington - North Carolina"]},
				{"Florida,Winter Haven":["W","Winter Haven"]}
		],
		"X": [],
		"Y": [],
		"Z": []
};

